# Generated by Django 5.1.7 on 2025-04-20 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('users', '0003_remove_user_nom_remove_user_prenom'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(blank=True, null=True)),
                ('date_passed', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.etudiant')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.evaluation')),
            ],
        ),
    ]
