# Generated by Django 5.1.7 on 2025-04-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_adresse_user_date_naissance_user_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prenom',
        ),
    ]
